# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         User-getgrouplist
version:      1.0.2
version_from: lib/User/getgrouplist.pm
installdirs:  site
requires:
    Exporter:                      0
    Test::Builder:                 0
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
