---
abstract: "Interface to glibc \"getgrouplist\" function"
author:
  - 'Bastian Friedrich <bastian.friedrich@collax.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: User-getgrouplist
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 0
  Test::Builder: 0
  Test::More: 0
version: v1.1.0
